/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-05-13 04:32:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.common.Cart;
import com.models.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.common.Cart");
    _jspx_imports_classes.add("com.models.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("   ");
  User user = (User)session.getAttribute("logged_user");
   		int size = Cart.getInstance().size();
   
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\"/>\r\n");
      out.write(" <link rel= \"stylesheet\" href=\"css/style.css\"/>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("a{\r\n");
      out.write("text-decoration: none;\r\n");
      out.write("color:#fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav{\r\n");
      out.write("background :linear-gradient(to left, #800080,#fff);\r\n");
      out.write("height  : 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav  a{\r\n");
      out.write("color  :#fff;\r\n");
      out.write("margin-left  :3%;\r\n");
      out.write("float: right;\r\n");
      out.write("height : 100%;\r\n");
      out.write("position : relative;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav a span{\r\n");
      out.write("\tpadding-top:15px;\r\n");
      out.write("\tdisplay:block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#ham{\r\n");
      out.write("float : left;\r\n");
      out.write("margin-left: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slide{\r\n");
      out.write("display : none;\r\n");
      out.write("position : absolute;\r\n");
      out.write("}\r\n");
      out.write(".fade {\r\n");
      out.write("-webkit-animation: fade 5s;\r\n");
      out.write("animation: fade 5s;\r\n");
      out.write("-moz-animation: fade 5s;\r\n");
      out.write("-o-animation: fade 5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover{\r\n");
      out.write("color : #00ffbf;\r\n");
      out.write("text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("#dropdown_menu{\r\n");
      out.write("position :absolute;\r\n");
      out.write("background :linear-gradient( #800080,#fff);\r\n");
      out.write("height : 100%;\r\n");
      out.write("width : 15%;\r\n");
      out.write("top : 0;\r\n");
      out.write("left : 0;\r\n");
      out.write("display : none;\r\n");
      out.write("z-index :1;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dropdown_list{\r\n");
      out.write("list-style-type:none;\r\n");
      out.write("padding-left : 5%;\r\n");
      out.write("margin-top : 15%;\r\n");
      out.write("margin-left : 10%;\r\n");
      out.write("color : #fff; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#dropdown_list li{\r\n");
      out.write("margin : 10%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login_div{\r\n");
      out.write("width :80%;\r\n");
      out.write("height :80%; \r\n");
      out.write("position : fixed;\r\n");
      out.write("top : 10%;\r\n");
      out.write("left : 10%;\r\n");
      out.write("display : none;\r\n");
      out.write("z-index :1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login-form{\r\n");
      out.write("margin:15%;\r\n");
      out.write("margin-left:30%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login-form input{\r\n");
      out.write("margin : 3%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menubar{\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("\tmargin-right:10px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".menubar li{\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tpadding:10px;\r\n");
      out.write("\tlist-style:none;\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("}\r\n");
      out.write(".menubar li a{\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("}\r\n");
      out.write(".menubar li:hover{\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".submenu{\r\n");
      out.write("\tmargin-top:10px;\r\n");
      out.write("}\r\n");
      out.write(".menubar a,.submenu a{\r\n");
      out.write("\tcursor:pointer;\r\n");
      out.write("}\r\n");
      out.write(" .submenu{\r\n");
      out.write(" \tdisplay:none;\r\n");
      out.write(" \tfloat:right;\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("    top: 40px;\r\n");
      out.write("    right: 00px;\r\n");
      out.write("    z-index : 5;\r\n");
      out.write("}\r\n");
      out.write(".submenu li{\r\n");
      out.write("\tbackground : #800080; \r\n");
      out.write("\tdisplay:block;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("}\r\n");
      out.write(".menubar li{\r\n");
      out.write("\tline-height:35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submenu  li {\r\n");
      out.write("padding : 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<nav>\r\n");
      out.write("<i class=\"fa fa-bars\" id=\"ham\" style=\"float:left;margin : 20px;\"></i>\r\n");
      out.write("<ul class=\"menubar\">\r\n");
      out.write("\r\n");
      out.write("\t<li>\r\n");
      out.write("\t\t<a href=\"home\"><i class=\"fa fa-home\">Home</i></a>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li>\r\n");
      out.write("\t<a href=\"show-category\"><i class=\"fa fa-list-alt\" aria-hidden=\"true\">Categories</i></a>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t\r\n");
      out.write("\t<li>\r\n");
      out.write("\t\t<a href=\"cart\"><i class=\"fa fa-shopping-cart\">Cart</i></a>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<li class=\" dropdown\" > \r\n");
      out.write("\t");
 if(user == null){ 
      out.write("\r\n");
      out.write("\t\t<a href=\"#\" id=\"login_btn\"><i class=\"fa fa-user\">LogIn</i></a>\r\n");
      out.write("\t");
}else{
		
      out.write("\r\n");
      out.write("\t\t\t<a href=\"#\"><i class=\"fa fa-user fa fa-angle-down\">");
      out.print(user!=null?user.getName().toUpperCase():"");
      out.write("</i>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<ul class=\"submenu\">\r\n");
      out.write("\t\t\t\t<li >\r\n");
      out.write("\t\t\t\t\t<a href=\"logout\">Logout</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t</a>\t\t");

	}
      out.write("\r\n");
      out.write("\t</li>\r\n");
      out.write("</ul>\t\r\n");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div id=\"login_div\" style=\"z-index:6\"> \r\n");
      out.write("<div style=\" float : left;background:blue; height : 100%;width:30%; border-radius:0px 0px 0px 90px;\"></div>\r\n");
      out.write("<div class=\"form-group\" style=\"float : right;background-image : url('images/login_img.png'); background-size:100% ,100%; background-repeat:no-repeat; height : 100%; width:70%;\">\r\n");
      out.write("<i id=\"close\" class=\"fa\" style=\"cursor:pointer;float : right; margin-right :1%;\">&#xf00d;</i>\r\n");
      out.write("<form id = \"login-form\" class=\"form-inline\" method=\"POST\" action=\"login\">\r\n");
      out.write("<input type=\"email\" class=\"form-control\" placeholder=\"Enter your email\" name= \"email\"/><br/>\r\n");
      out.write("<input type=\"password\" class=\"form-control\" placeholder=\"Enter your password\"name=\"password\"/><br/>\r\n");
      out.write("<input type=\"hidden\" name=\"redirect\" value=\"\"/>\r\n");
      out.write("<input type = \"submit\" class=\"form-control\" class=\"mylinks\" value=\"LogIn\"/>\r\n");
      out.write("</form>\r\n");
      out.write("<a href=\"signup\" style=\"margin-left : 35%\">New User?Sign up</a>\r\n");
      out.write("<button class=\"mylinks_xsmall\" onclick=\"signIn();\">Signin with Google</button>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id =\"dropdown_menu\">\r\n");
      out.write("<ul id=\"dropdown_list\">\r\n");
      out.write("<li >Home</li>\r\n");
      out.write("<li><a href=\"show-category\">categories</a></li>\r\n");
      out.write("<li><a href=\"cart\">Cart</a></li> \r\n");
      out.write("<li>About us</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<hr/>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!-- The core Firebase JS SDK is always required and must be listed first -->\r\n");
      out.write("<script src=\"https://www.gstatic.com/firebasejs/6.3.3/firebase-app.js\"></script>\r\n");
      out.write("  <script src=\"https://www.gstatic.com/firebasejs/6.3.3/firebase-auth.js\"></script>\r\n");
      out.write("  <script src=\"https://www.gstatic.com/firebasejs/6.3.3/firebase-firestore.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<!-- TODO: Add SDKs for Firebase products that you want to use\r\n");
      out.write("     https://firebase.google.com/docs/web/setup#config-web-app -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(\".dropdown\").click(function(){\r\n");
      out.write("\t$(\".submenu\").toggle();\r\n");
      out.write("});\r\n");
      out.write("  // Your web app's Firebase configuration\r\n");
      out.write("  var firebaseConfig = {\r\n");
      out.write("    apiKey: \"AIzaSyCvFhIJKpqIUkRoxaZlACwL46kBiOLOR6M\",\r\n");
      out.write("    authDomain: \"webproject-72b83.firebaseapp.com\",\r\n");
      out.write("    databaseURL: \"https://webproject-72b83.firebaseio.com\",\r\n");
      out.write("    projectId: \"webproject-72b83\",\r\n");
      out.write("    storageBucket: \"\",\r\n");
      out.write("    messagingSenderId: \"1035293713734\",\r\n");
      out.write("    appId: \"1:1035293713734:web:aff3812543bf6e53\"\r\n");
      out.write("  };\r\n");
      out.write("  // Initialize Firebase\r\n");
      out.write("  firebase.initializeApp(firebaseConfig);\r\n");
      out.write("\r\n");
      out.write("var provider = new firebase.auth.GoogleAuthProvider();\r\n");
      out.write("provider.addScope('https://www.googleapis.com/auth/contacts.readonly');\r\n");
      out.write("firebase.auth().languageCode = 'en';\r\n");
      out.write("function signIn(){/*\r\n");
      out.write("\tfirebase.auth().signInWithPopup(provider).then(function(result) {\r\n");
      out.write("\t\t  // This gives you a Google Access Token. You can use it to access the Google API.\r\n");
      out.write("\t\t  var token = result.credential.accessToken;\r\n");
      out.write("\t\t  // The signed-in user info.\r\n");
      out.write("\t\t  var user = result.user;\r\n");
      out.write("\t\t  // ...\r\n");
      out.write("\t\t}).catch(function(error) {\r\n");
      out.write("\t\t  // Handle Errors here.\r\n");
      out.write("\t\t  var errorCode = error.code;\r\n");
      out.write("\t\t  var errorMessage = error.message;\r\n");
      out.write("\t\t  // The email of the user's account used.\r\n");
      out.write("\t\t  var email = error.email;\r\n");
      out.write("\t\t  // The firebase.auth.AuthCredential type that was used.\r\n");
      out.write("\t\t  var credential = error.credential;\r\n");
      out.write("\t\t  // ...\r\n");
      out.write("\t\t});\r\n");
      out.write("\t*/\r\n");
      out.write("\tfirebase.auth().signInWithRedirect(provider);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function sendSigninDetails(userData){\r\n");
      out.write("\r\n");
      out.write("\tvar obj = new XMLHttpRequest();\r\n");
      out.write("\tvar URL=\"http://localhost:8080/myproject/signin-with-google\";\r\n");
      out.write("\tobj.open(\"POST\",URL,true);\r\n");
      out.write("\tobj.send(userData);\r\n");
      out.write("\tobj.onreadystatechange = function () {\r\n");
      out.write("\t\tif(this.readyState == 4 && this.status == 200){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(this.responseText==\"success\"){\r\n");
      out.write("\t\t\t\twindow.location.href=\"\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\talert(\"Failed to signin\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("firebase.auth().getRedirectResult().then(function(result) {\r\n");
      out.write("\t  if (result.credential) {\r\n");
      out.write("\t    // This gives you a Google Access Token. You can use it to access the Google API.\r\n");
      out.write("\t    var token = result.credential.accessToken;\r\n");
      out.write("\t    // ...\r\n");
      out.write("\t  }\r\n");
      out.write("\t  // The signed-in user info.\r\n");
      out.write("\t  var user = result.user;\r\n");
      out.write("\t  if(user!=null){\r\n");
      out.write("\t\t  alert(\"success\");\r\n");
      out.write("\t\t  alert(JSON.stringify(user)); \r\n");
      out.write("\t\t  sendSigninDetails(JSON.stringify(user));\r\n");
      out.write("\t  }\r\n");
      out.write(" }).catch(function(error) {\r\n");
      out.write("\t  // Handle Errors here.\r\n");
      out.write("\t  var errorCode = error.code;\r\n");
      out.write("\t  var errorMessage = error.message;\r\n");
      out.write("\t  // The email of the user's account used.\r\n");
      out.write("\t  var email = error.email;\r\n");
      out.write("\t  // The firebase.auth.AuthCredential type that was used.\r\n");
      out.write("\t  var credential = error.credential;\r\n");
      out.write("\t  // ...\r\n");
      out.write("\t  alert(\"failed\"+errorMessage);\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\"#ham\").hover(function(){\r\n");
      out.write("\t$(\"#dropdown_menu\").show(80);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(document).click(function(){\r\n");
      out.write("\t$(\"#dropdown_menu\").hide(80);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#login_btn\").click(function(){\r\n");
      out.write("\t$(\"#login_div\").show();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#close\").click(\r\n");
      out.write("\t\tfunction(){\r\n");
      out.write("\t\t\t$(\"#login_div\").hide();\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
